name: CI / lint-en-test

# ── Wanneer moet de workflow draaien? ───────────────────────────────────────────
on:
  pull_request:            # én elk PR richting main of develop
    branches: [main, develop]

# ── Eén job: build ─────────────────────────────────────────────────────────────
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4            # haalt de repo-code op

      - uses: actions/setup-node@v4          # installeert Node + npm
        with:
          node-version: 20                   # kies je Node-versie

      - run: npm install                     # installeert dependencies

      - run: npm run lint || true            # lint (|| true → geen lint? job slaagt toch)

      - run: npm run test || true            # tests (idem)
